version: '3.9'

services:
  amplifier:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 4000:4000
    volumes:
      - .:/amplifier
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - ENV=dev
      - REDIS_URL=redis://:MDNcVb924a@redis:6379

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass MDNcVb924a

  workwebui:
    image: ektowett/workwebui:latest
    ports:
      - 5040:5040
    depends_on:
      - "redis"
    environment:
      - REDIS_NAMESPACE=amplifier
      - REDIS_HOST=redis://:MDNcVb924a@redis:6379
