version: '3.9'

services:
  amplifier:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - ENV=dev
      - DB_URL=postgres://amplifier:amplifier@postgres/amplifier?sslmode=disable
      - REDIS_URL=redis://:MDNcVb924a@redis:6379

  postgres:
    image: postgres:13.2-alpine
    # ports:
    #   - 5432:5432
    volumes:
      - ~/apps/amplifier/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=amplifier
      - POSTGRES_USER=amplifier
      - POSTGRES_DB=amplifier

  redis:
    image: redis:6.2-alpine
    # ports:
    #   - 6379:6379
    command: redis-server --requirepass MDNcVb924a

  workwebui:
    image: ektowett/workwebui:latest
    # ports:
    #   - 5040:5040
    depends_on:
      - "redis"
    environment:
      - REDIS_NAMESPACE=amplifier
      - REDIS_HOST=redis://:MDNcVb924a@redis:6379
