replicaCount: 1

image:
  repository: ektowett/amplifier
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "amplifier"
fullnameOverride: "amplifier"

serviceAccount:
  create: false

podSecurityContext: {}

securityContext: {}

persistence:
  enabled: false

hook:
  name: db-migrate
  image:
    repository: ektowett/amplifier-migrate
    tag: latest
    pullPolicy: IfNotPresent
  commands:
    - command: /go/bin/goose -dir /migrations postgres "${DB_URL}" up
  ttlSecondsAfterFinished: 0
  backoffLimit: 2
  activeDeadlineSeconds: 100

containerPort: 4000
containerName: http

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev-amplifier.kip0127.cloud.okteto.net
      paths:
        - "/"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  PORT: "4000"
  ENV: dev
  DB_URL: postgres://dev_amplifier:PyLRXPNmLoS3E89h7@3.249.127.82:5432/dev_amplifier
  REDIS_URL: redis://:T8mRbhtyjfspceQeYZn6XFc53WZa9NvW@3.249.127.82:6379
